# Table of content
#
- file: content/theme/eleve

- part: Première année
  numbered: false
  chapters:
  - file: content/theme/representation-information/eleve
    sections:
      - file: content/theme/representation-information/representation-entiers/eleve
      - file: content/theme/representation-information/representation-caracteres/eleve
      - file: content/theme/representation-information/representation-images/eleve
      - file: content/theme/representation-information/numerisation/eleve
      - file: content/theme/representation-information/systeme-arithmetique-binaire/eleve
      - file: content/theme/representation-information/stockage-manipulation-donnees/eleve
      - file: content/theme/representation-information/redondance/eleve
      - file: content/theme/representation-information/exercices
        sections:
          - file: content/theme/representation-information/representation-caracteres/exercice/carte-perforee/exercice
      - file: content/theme/representation-information/activites
        sections:
          - file: content/theme/representation-information/representation-entiers/activite/magie-binaire/magie_binaire
  - file: content/theme/introduction-algorithmique/eleve
    sections:
      - file: content/theme/introduction-algorithmique/decomposition-probleme/eleve
      - file: content/theme/introduction-algorithmique/algorithmes-classiques/eleve
      - file: content/theme/introduction-algorithmique/formulation-solutions/eleve
      - file: content/theme/introduction-algorithmique/consequences-automatisation/eleve
  - file: content/theme/programmation/eleve
    sections:
      - file: content/theme/programmation/0_intro/intro
      - file: content/theme/programmation/1_intro/intro 
      - file: content/theme/programmation/2_pyth/pyth
      - file: content/theme/programmation/3_var/var
      - file: content/theme/programmation/4_flux/flux
      - file: content/theme/programmation/5_list/list
      - file: content/theme/programmation/6_dict/dict
      - file: content/theme/programmation/7_fonc/fonc
      - file: content/theme/programmation/8_mod/mod
      - file: content/theme/programmation/9_app/app 
  - file: content/theme/architecture-ordinateurs/eleve
    sections:
      - file: content/theme/architecture-ordinateurs/introduction
      - file: content/theme/architecture-ordinateurs/systemes-logiques/eleve
        sections: 
          - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SystemesLogiques
            sections:
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL1_bases
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL2_portes
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL3_sl
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL4_avance
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL5_conclusion
          - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/Corrige_SystemesLogiques
      - file: content/theme/architecture-ordinateurs/architecture-von-neumann/eleve
      - file: content/theme/architecture-ordinateurs/microprocesseur/eleve
      - file: content/theme/architecture-ordinateurs/elements-base-ordinateurs/eleve
      - file: content/theme/architecture-ordinateurs/informatique-embarquee/eleve
      - file: content/theme/architecture-ordinateurs/histoire-informatique/eleve
      - file: content/theme/architecture-ordinateurs/ressources
- part: Deuxième année
  numbered: false
  chapters:
  - file: content/theme/algorithmique-programmation/eleve
  - file: content/theme/projets/eleve
  - file: content/theme/reseaux/eleve

- part: Démos et divers
  numbered: false
  chapters:
  - file: content/demostests/glossaire
  - file: content/demostests/edito/syntaxemyst
  - file: content/demostests/edito/presentation-ressources
  - file: content/demostests/edito/liens
  - file: content/demostests/edito/referencesart
  - file: content/demostests/edito/testaccueilrepinfo
  - file: content/demostests/edito/testintrorepinfo

# Ajout d'une partie pour les enjeux sociaux

#- part: Enjeux sociaux
#  numbered: false
#  chapters:
#  - file: 

# - part: À affecter
#  numbered: false
#  chapters:
#  - file: content/annexe/eleve
#  - file: content/playground/eleve
#    sections:
#      - file: content/playground/notebook
#      - file: content/playground/types
#  - file: content/arts/L'app de rencontre
#  - file: content/arts/La poésie des limites
#  - file: content/arts/Python_turtle_extension
#  - file: content/arts/Qui suis-je_retouchesOlivier
#  - file: content/arts/contemporain_final
#  - file: content/enjeux/digital-labor/eleve
#  - file: content/fiche/references-notebook
#  - file: content/theme/algorithmique-programmation/activites/Cupidon est un programme
#  - file: content/theme/algorithmique-programmation/activites/La recette de l'univers
#  - file: content/theme/algorithmique-programmation/activites/Crucial Kruskal
#  - file: content/theme/introduction-algorithmique/algorithmes-classiques/activite/dijkstra/dijkstra
