# Table of content
#
- file: content/theme/eleve

- part: Première année
  numbered: false
  chapters:
  - file: content/theme/representation-information/eleve
    sections:
      - file: content/theme/representation-information/representation-entiers/eleve
      - file: content/theme/representation-information/representation-caracteres/eleve
      - file: content/theme/representation-information/representation-images/eleve
      - file: content/theme/representation-information/numerisation/eleve
      - file: content/theme/representation-information/systeme-arithmetique-binaire/eleve
      - file: content/theme/representation-information/stockage-manipulation-donnees/eleve
      - file: content/theme/representation-information/redondance/eleve
      - file: content/theme/representation-information/enjeu/transformation-numerique-economie-droit/eleve
      - file: content/theme/representation-information/exercices
        sections:
          - file: content/theme/representation-information/representation-caracteres/exercice/carte-perforee/exercice
  - file: content/theme/introduction-algorithmique/eleve
    sections:
      - file: content/theme/introduction-algorithmique/decomposition-probleme/eleve
      - file: content/theme/introduction-algorithmique/algorithmes-classiques/eleve
      - file: content/theme/introduction-algorithmique/formulation-solutions/eleve
      - file: content/theme/introduction-algorithmique/consequences-automatisation/eleve
  - file: content/theme/introduction-programmation/eleve
    sections:
      - file: content/theme/introduction-programmation/instructions-sequentielles/eleve
      - file: content/theme/introduction-programmation/structures-donnees-controle/eleve
      - file: content/theme/introduction-programmation/transcription-algorithmes/eleve
      - file: content/theme/introduction-programmation/perspectives-citoyennes-politiques/eleve
  - file: content/theme/architecture-ordinateurs/eleve
    sections:
      - file: content/theme/architecture-ordinateurs/introduction
      - file: content/theme/architecture-ordinateurs/systemes-logiques/eleve
        sections: 
          - file: content/theme/architecture-ordinateurs/systemes-logiques/conclusion
          - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SystemesLogiques
            sections:
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL1_bases
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL2_portes
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL3_sl
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL4_avance
              - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/SL5_conclusion
          - file: content/theme/architecture-ordinateurs/systemes-logiques/exercice/Corrige_SystemesLogiques
      - file: content/theme/architecture-ordinateurs/architecture-von-neumann/eleve
      - file: content/theme/architecture-ordinateurs/microprocesseur/eleve
      - file: content/theme/architecture-ordinateurs/elements-base-ordinateurs/eleve
      - file: content/theme/architecture-ordinateurs/informatique-embarquee/eleve
      - file: content/theme/architecture-ordinateurs/histoire-informatique/eleve
      - file: content/theme/architecture-ordinateurs/ressources
- part: Deuxième année
  numbered: false
  chapters:
  - file: content/theme/algorithmique-programmation/eleve
  - file: content/theme/projets/eleve
  - file: content/theme/reseaux/eleve

- part: À affecter
  numbered: false
  chapters:
  - file: content/annexe/eleve
  - file: content/playground/eleve
    sections:
      - file: content/playground/notebook
      - file: content/playground/types
  - file: content/arts/L'app de rencontre
  - file: content/arts/La poésie des limites
  - file: content/arts/Python_turtle_extension
  - file: content/arts/Qui suis-je_retouchesOlivier
  - file: content/arts/contemporain_final
  - file: content/enjeux/digital-labor/eleve
  - file: content/fiche/references-notebook
  - file: content/theme/algorithmique-programmation/activites/Cupidon est un programme
  - file: content/theme/algorithmique-programmation/activites/La recette de l'univers
  - file: content/theme/algorithmique-programmation/activites/Crucial Kruskal
  - file: content/theme/introduction-algorithmique/algorithmes-classiques/activite/dijkstra/dijkstra
