# Table of content
#
- file: content/theme/maitre
- file: content/theme/representation-information/maitre
  sections:
    - file: content/theme/representation-information/representation-entiers/maitre
#    - file: content/theme/representation-information/systeme-arithmetique-binaire/maitre
#    - file: content/theme/representation-information/stockage-manipulation-donnees/maitre
#   - file: content/theme/representation-information/redondance/maitre
#    - file: content/theme/representation-information/enjeu/transformation-numerique-economie-droit/maitre
    - file: content/theme/representation-information/activites
      sections:
        - file: content/theme/representation-information/activites/representation-entiers/activite/magie-binaire/magie_binaire
        - file: content/theme/representation-information/activites/representation-images/activite/bitmap
- file: content/theme/introduction-algorithmique/maitre
  sections:
  #  - file: content/theme/introduction-algorithmique/decomposition-probleme/maitre
  #  - file: content/theme/introduction-algorithmique/algorithmes-classiques/maitre
    - file: content/theme/introduction-algorithmique/activites/algorithmes-classiques/algo-tri/algo-tri
    - file: content/theme/introduction-algorithmique/activites/algorithmes-classiques/epidemie/epidemie
      sections:
        - file: content/theme/introduction-algorithmique/activites/algorithmes-classiques/epidemie/fiche
    - file: content/theme/introduction-algorithmique/activites/algorithmes-classiques/dijkstra/dijkstra2
    - file: content/theme/introduction-algorithmique/activites/algorithmes-classiques/puissance4/puissance4
    - file: content/theme/introduction-algorithmique/activites/formulation-solutions/maitre
    - file: content/theme/introduction-algorithmique/consequences-automatisation/maitre
- file: content/theme/programmation/maitre
  sections:
    - file: content/theme/programmation/instructions-sequentielles/maitre
    - file: content/theme/programmation/structures-donnees-controle/maitre
    - file: content/theme/programmation/transcription-algorithmes/maitre
    - file: content/theme/programmation/perspectives-citoyennes-politiques/maitre
    - file: content/theme/programmation/activites
      sections:
        - file: content/theme/programmation/activites/microbit/catch-the-fruit/catchFruit
- file: content/theme/architecture-ordinateurs/maitre
  sections:
    - file: content/theme/architecture-ordinateurs/systemes-logiques/maitre
    - file: content/theme/architecture-ordinateurs/microprocesseur/maitre
    - file: content/theme/architecture-ordinateurs/elements-base-ordinateurs/maitre
    - file: content/theme/architecture-ordinateurs/architecture-von-neumann/maitre
    - file: content/theme/architecture-ordinateurs/informatique-embarquee/maitre
    - file: content/theme/architecture-ordinateurs/histoire-informatique/maitre
- file: content/annexe/maitre
- file: content/playground/maitre
  sections:
    - file: content/playground/notebook
    - file: content/playground/types

