# Table of content
#
- file: content/demostests/edito/landing

- part: Première année
  numbered: false
  chapters:
  - file: content/theme/representation-information/01_accueil/eleve
    sections:
      - file: content/theme/representation-information/introduction/eleve
      - file: content/theme/representation-information/representation-entiers/eleve
      - file: content/theme/representation-information/representation-caracteres/eleve
      - file: content/theme/representation-information/representation-images/eleve
      - file: content/theme/representation-information/numerisation/eleve
      - file: content/theme/representation-information/systeme-arithmetique-binaire/eleve
      - file: content/theme/representation-information/stockage-manipulation-donnees/eleve
      - file: content/theme/representation-information/redondance/eleve
      - file: content/theme/representation-information/03_exercices/exercices
        sections:
          - file: content/theme/representation-information/03_exercices/representation-caracteres/carte-perforee/exercice
      - file: content/theme/representation-information/00_activites/activites
        sections:
          - file: content/theme/representation-information/00_activites/representation-entiers/magie-binaire/magie_binaire
          - file: content/theme/representation-information/00_activites/redondance/radiotelephonie/activite
  - file: content/theme/introduction-algorithmique/eleve
    sections:
      - file: content/theme/introduction-algorithmique/decomposition-probleme/eleve
      - file: content/theme/introduction-algorithmique/algorithmes-classiques/eleve
      - file: content/theme/introduction-algorithmique/formulation-solutions/eleve
      - file: content/theme/introduction-algorithmique/consequences-automatisation/eleve
  - file: content/theme/programmation/eleve
    sections:
      - file: content/theme/programmation/0_intro/intro
      - file: content/theme/programmation/1_intro/intro 
      - file: content/theme/programmation/2_pyth/pyth
      - file: content/theme/programmation/3_var/var
      - file: content/theme/programmation/4_flux/flux
      - file: content/theme/programmation/5_list/list
      - file: content/theme/programmation/6_dict/dict
      - file: content/theme/programmation/7_fonc/fonc
      - file: content/theme/programmation/8_mod/mod
      - file: content/theme/programmation/9_app/app 
  - file: content/theme/architecture-ordinateurs/accueil
    sections:
      - file: content/theme/architecture-ordinateurs/introduction
      - file: content/theme/architecture-ordinateurs/portes-logiques/eleve
      - file: content/theme/architecture-ordinateurs/de-logique-a-arithmetique/eleve
      - file: content/theme/architecture-ordinateurs/alu-bascules/eleve
        sections: 
          - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SystemesLogiques
            sections:
              - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SL1_bases
              - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SL2_portes
              - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SL3_sl
              - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SL4_avance
              - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/SL5_conclusion
          - file: content/theme/architecture-ordinateurs/alu-bascules/exercice/Corrige_SystemesLogiques
      - file: content/theme/architecture-ordinateurs/architecture-von-neumann/eleve
      - file: content/theme/architecture-ordinateurs/microprocesseur/eleve
      - file: content/theme/architecture-ordinateurs/informatique-embarquee/eleve
      - file: content/theme/architecture-ordinateurs/histoire-informatique/eleve
      - file: content/theme/architecture-ordinateurs/ressources
- part: Deuxième année
  numbered: false
  chapters:
  - file: content/theme/algorithmique-avancee/eleve
    sections:
      - file: content/theme/algorithmique-avancee/terminaison/eleve
      - file: content/theme/algorithmique-avancee/complexite/eleve
      - file: content/theme/algorithmique-avancee/heuristiques/eleve
      - file: content/theme/algorithmique-avancee/conclusion/eleve
  - file: content/theme/programmation-avancee/eleve
  - file: content/theme/projets/eleve
  - file: content/theme/reseaux/eleve

- part: Enjeux sociaux
  numbered: false
  chapters:
  - file: content/enjeux/grandes-thematiques/grandes-thematiques
    sections:
    - file: content/enjeux/grandes-thematiques/economie-numerique/economie-numerique
  - file: content/enjeux/fiches-complementaires/fiches-complementaires
    sections:
    - file: content/enjeux/fiches-complementaires/digital-labor/digital-labor
    - file: content/enjeux/fiches-complementaires/wikipedia/wikipedia
  - file: content/enjeux/bibliographie


- part: Démos et divers
  numbered: false
  chapters:
  - file: content/demostests/glossaire
  - file: content/demostests/glossaire1
  - file: content/demostests/edito/liens
  # - file: content/demostests/edito/referencesart
  - file: content/demostests/edito/extensions
  - file: content/demostests/edito/Redaction-Bonnes-pratiques
  - file: content/demostests/art/histoireart
  # - file: content/demostests/edito/repinfo1test
  - file: content/theme/architecture-ordinateurs/introductiontest

- part: README
  numbered: false
  chapters:
  - file: content/demostests/edito/presentation-ressources
    sections: 
      - file: content/demostests/edito/exempleutilisation
      - file: content/demostests/edito/modificationsressources
      - file: content/demostests/edito/participation-developpement
      - file: content/demostests/edito/syntaxemyst
      - file: content/demostests/edito/relectures


