# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Informatique en tant que discipline obligatoire — Version enseignant·e — Canton de Vaud, 2020
author: Groupe de travail DGEP, EPFL, HEP, UNIL
logo: logo.png
exclude_patterns: ['**/eleve.md']

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: maitre.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/edunum-sec2/ressources  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  local_extensions:
    questions: ../extensions/
